### ISSUE TITLE
Two broken urls

### ISSUE THREAD

**Issue by noelmcloughlin** [cuelang/cuelang.org#1]
These two landing page urls are broken

cuelang.org/cue
cuelang.org/x

**Comment by mpvl** [comment]
Should be fixed now. :)

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/1.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
