### ISSUE TITLE
Include link to playground in the documentation site 

### ISSUE THREAD

**Issue by anik120** [cuelang/cuelang.org#110]
I was trying to find the link to the playground for CUE, and doesn't look like it's easiest to find. Including a link to the CUE playground in the documentation site can help readers find the CUE playground faster.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/110.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
