### ISSUE TITLE
Closed structs

### ISSUE THREAD

**Issue by tebeka** [cuelang/cuelang.org#118]
The text says:

> A closed struct can be created using the closed builtin, but are more commonly defined using a definition, defined next.

But the code has:
```cue
a: close({
    field: int
})
```

Missing `d`?

**Comment by myitcv** [comment]
No, the paragraph has an error. Thanks for pointing this out. The builtin is called `close`.

**Comment by myitcv** [comment]
Raised https://cue-review.googlesource.com/c/cue/+/8066 to fix this

**Comment by myitcv** [comment]
This was fixed in the referenced commit.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/118.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
