### ISSUE TITLE
site: using Netlify is slow

### ISSUE THREAD

**Issue by myitcv** [cuelang/cuelang.org#124]
The benefit of Netlify is that it offers a nice way to preview changes from different PRs.

But it's slow, particular when it comes to the playground. 

What options do we have here?

**Comment by myitcv** [comment]
Raised an issue with Netlify, because this does appear to be an issue on their end:

https://community.netlify.com/t/very-large-variation-in-download-speeds/29688

One option is to move to hosting the site on GitHub pages which does not suffer this problem. This would require use to host play.cuelang.org (and play.tip.cuelang.org), but retain the Netlify hosting to act as a proxy (with suitable CORS configuration) for the use of play.golang.org storage.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/124.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
