### ISSUE TITLE
Type Hierarchy

### ISSUE THREAD

**Issue by j-bai** [cuelang/cuelang.org#126]
In the given example, definitions of *xaxis* and *yaxis* are obviously incorrect: for all points on *xaxis*, their *y* coordinates should always be *0*; similarly, for all points on *yaxis*, their *x* coordinates should always be *0*. Therefore, content of *types.cue* should be as below:

> point: {
> 	x: number
> 	y: number
> }
> 
> xaxis: point
> xaxis: y: 0
> 
> yaxis: point
> yaxis: x: 0
> 
> origin: xaxis & yaxis

**Comment by myitcv** [comment]
This was resolved by a commit referenced above.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/126.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
