### ISSUE TITLE
usecases/datadef: overly technical content in "On logical not" section

### ISSUE THREAD

**Issue by extemporalgenome** [cuelang/cuelang.org#130]
https://cuelang.org/docs/usecases/datadef/#json-schema--openapi

"On logical not" has content that is perhaps overly technical for a use-cases page. Many readers may not be familiar with the symbols for not and false/bottom, and may get the false impression that CUE is too academic/theoretical for them to learn and start using (or that CUE has important limitations in its integration with OpenAPI, despite "not" being comparatively rare).

The "On logical not" guidance may be more suited for an errata page specific to OpenAPI, and it would be consumable by a wider audience using CUE syntax (or something approximating it) to represent the dilemma and workaround.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1987.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
