### ISSUE TITLE
usecases/datadef.md: thin contrast with CDDL

### ISSUE THREAD

**Issue by extemporalgenome** [cuelang/cuelang.org#131]
> Unlike OpenAPI, CDDL is a domain-specific language (DSL). It needs a specific interpreter. It also has some non-trivial aspects to its evaluation, making it much harder than OpenAPI to implement.

Arguably the same arguments could be made against CUE itself: it's a language, thus needs a language implementation, and the CUE tooling presumably required a non-trivial amount of thought and effort, thus making it harder than OpenAPI to [semantically] implement.

This really feels like it should be a maturity/consistency argument: CUE is a multi-purpose language for which a primary implementation is _provided_, whereas CDDL is a limited-scope language meant to be treated more as a data-interchange format, with the intention that implementations (of inconsistent quality) be developed for use in various host languages or tools.

**Comment by myitcv** [comment]
cc @mpvl

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1986.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
