### ISSUE TITLE
Tour should be regenerated

### ISSUE THREAD

**Issue by extemporalgenome** [cuelang/cuelang.org#135]
The page https://cuelang.org/docs/tutorials/tour/intro/schema/ is inconsistent with source text from https://github.com/cuelang/cue/blob/732b6d57a9d8e172509f02dd1bdd13969c4d50bc/doc/tutorial/basics/2_types/55_defs.txt

("starting with **a** `#`" instead of the more correct phrasing "starting with `#`")

**Comment by extemporalgenome** [comment]
I was wrong. It turns out there are, confusingly, two "definitions" lessons in the tour.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/135.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
