### ISSUE TITLE
Type Hierarchy doc: x-axis & y-axis are mixed up

### ISSUE THREAD

**Issue by assaflavi** [cuelang/cuelang.org#145]
In the [Type Hierarchy](https://cuelang.org/docs/tutorials/tour/types/types/) page, the example defines `xaxis` as an incomplete instance of `point` where `x == 0`:
```
xaxis: point
xaxis: x: 0
```

That is actually wrong, as an x-axis is all the points with `y == 0`.

A corresponding argument applies to the `yaxis` example.

**Comment by assaflavi** [comment]
Oops, just noticed this duplicates [an existing issue](https://github.com/cuelang/cuelang.org/issues/126) that was already fixed.

Never mind.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/145.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
