### ISSUE TITLE
Show cue version number in docs

### ISSUE THREAD

**Issue by jugaadi** [cuelang/cuelang.org#178]
With lot of language proposals in pipeline, it would be better if cue version is shown in the docs. This can also help users access the docs of previous versions.

**Comment by myitcv** [comment]
This is a great suggestion. Whilst it could be implied that the docs reflect `cuelang.org/go@latest`, being explicit would be much clearer (especially when it comes to https://tip.cuelang.org/)

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1985.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
