### ISSUE TITLE
List of language bindings needed somehwere.

### ISSUE THREAD

**Issue by paul-hammant** [cuelang/cuelang.org#27]
1. Go - available now
2. JavaScript - repo created, but no code yet

Similarly, the prominent 'download' link should indicate what would be downloaded precisely.

**Comment by myitcv** [comment]
Apologies for taking so long to get round to this @paul-hammant.

The official list of integrations is here: https://cuelang.org/docs/integrations/

Discussion about other language integrations/etc is happening in the main repo, e.g. https://github.com/cuelang/cue/issues/86, https://github.com/cuelang/cue/issues/162 and https://github.com/cuelang/cue/issues/356

> Similarly, the prominent 'download' link should indicate what would be downloaded precisely.

I assume you're referring to the main download link on https://cuelang.org. I think the "Getting Started" guide provides sufficient distinction? 

https://cuelang.org/docs/install/

Would be interested if you have further suggestions on what could be tweaked there (I'm going to submit a change now to change _The Go APIs can be used as is using Go’s package manager_ to instead be a reference to Go modules)

As ever, docs could always be improved so greatly appreciate the feedback (despite it taking this long to reply)

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1993.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
