### ISSUE TITLE
theme/docsy: edit page link doesn't work for generated pages

### ISSUE THREAD

**Issue by xinau** [cuelang/cuelang.org#43]
since some pages are being generated/copied from the cuelang/cue repository the edit page button points to missing files on github for cuelang/cuelang.org

affected pages:
* https://cuelang.org/docs/references/spec/
* https://cuelang.org/docs/tutorials/tour/

a possible solution could be to override the href via the metadata in the generated markdown file and a custom template

**Comment by NReilingh** [comment]
Related to this, somewhere in contributing or readme it should say where one would go if they would like to submit an edit PR to, say, the tutorial. I wanted to fix some typos but gave up since it doesn't seem to be on GitHub.

**Comment by myitcv** [comment]
Thanks for flagging this @xinau and @NReilingh. 

@xinau - we'd happily accept/explore a PR that looked at fixing this "properly" along the lines you suggest. Alternatively in the short term we could simply include a comment in each file stating its source.

@NReilingh thank you for your recent changes, and sorry you couldn't find the spec/tutorial link. The are as follows:

* Spec: https://github.com/cuelang/cue/blob/master/doc/ref/spec.md
* Tour: https://github.com/cuelang/cue/tree/master/doc/tutorial/basics
* Kubernetes: https://github.com/cuelang/cue/tree/master/doc/tutorial/kubernetes

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1992.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
