### ISSUE TITLE
content: description of the current project maturity

### ISSUE THREAD

**Issue by xinau** [cuelang/cuelang.org#51]
similar to https://metallb.universe.tf/concepts/maturity/ or https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages it could be nice for newcomers and potential adopters to know what the current maturity guarantees are of the project. This might include topics like:

* adoption
* test coverage and thus probability of bugs
* developers (how many people are working on cue)
* expectation of breaking changes

**Comment by myitcv** [comment]
As we are getting closer to v1.0.0, @mpvl - might well be worth having something on this?

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1991.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
