### ISSUE TITLE
all: add instructions for updating documentation to Readme

### ISSUE THREAD

**Issue by mpvl** [cuelang/cuelang.org#52]
For instance:
- how to update the cue repo
- how to add graphs and illustrations
- other guidelines

**Comment by myitcv** [comment]
Somewhat addressed by https://github.com/cuelang/cuelang.org/pull/68

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1990.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
