### ISSUE TITLE
community: "contribution guidelines" is a 404

### ISSUE THREAD

**Issue by mvdan** [cuelang/cuelang.org#65]
See https://cuelang.org/community/, which takes you to https://cuelang.org/docs/contribution-guidelines/.

**Comment by myitcv** [comment]
This looks to have been fixed: https://cuelang.org/community/ now links to https://github.com/cuelang/cue/blob/master/CONTRIBUTING.md

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/65.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
