### ISSUE TITLE
netlify: add redirects for /issue

### ISSUE THREAD

**Issue by mvdan** [cuelang/cuelang.org#66]
To mirror golang.org. `/issues?/(.*)` redirects to `github.com/cuelang/cue/issues/<id>`.

This is particularly useful for Gerrit, since issue IDs don't work when reviewing, and it's easy to type `cuelang.org/issue/X` on the browser.

I'll be taking a look at this soon.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/66.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
