### ISSUE TITLE
Commit generated content (spec and tour)

### ISSUE THREAD

**Issue by myitcv** [cuelang/cuelang.org#77]
Because the language spec and tour are not generated we get funny artefacts like this at the bottom of either page:

<img width="371" alt="Screen Shot 2020-03-17 at 10 04 14" src="https://user-images.githubusercontent.com/3374574/76848637-f15d3c80-683b-11ea-8e25-b59e48430f00.png">

We should commit the generated result in any case to reduce the number of steps required to develop the site locally. 

This would involve:

* Dropping [`.gitignore`](https://github.com/cuelang/cuelang.org/blob/master/.gitignore) of generated spec and tour files
* Changing the [`update_tip`](https://github.com/cuelang/cuelang.org/blob/master/.github/workflows/update_tip.yml) workflow to be a `repository_dispatch` action that creates a new commit with the re-generated tip site instead of simply force pushing so that `tip` matches `master`. On `master` builds use https://github.com/marketplace/actions/repository-dispatch to trigger this action
* Adding `cueckoo` as a user with "Write" access to this repo
* Create an access token for `cueckoo` that is added as a secret in the github.com/cuelang/cue repo
* Changing the main CUE repository [rebuild tip](https://github.com/cuelang/cue/blob/master/.github/workflows/rebuild_tip_cuelang_org.yml) workflow to instead use https://github.com/marketplace/actions/repository-dispatch

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/77.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
