### ISSUE TITLE
spec: heading stutter at the top of the page

### ISSUE THREAD

**Issue by myitcv** [cuelang/cuelang.org#78]
Currently we get two headings at the top of the spec:

<img width="997" alt="Screen Shot 2020-03-17 at 11 19 30" src="https://user-images.githubusercontent.com/3374574/76851468-30da5780-6841-11ea-8997-621667350d00.png">

Whereas we only need one:

![no_stutter](https://user-images.githubusercontent.com/3374574/76851404-1b652d80-6841-11ea-8a7c-4e78e90c05ab.png)

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/78.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
