### ISSUE TITLE
tutorials: "basics tour" link goes to dead end on GitHub

### ISSUE THREAD

**Issue by myitcv** [cuelang/cuelang.org#80]
On https://cuelang.org/docs/tutorials/ the following link:

<img width="887" alt="Screen Shot 2020-03-17 at 11 25 14" src="https://user-images.githubusercontent.com/3374574/76851929-22407000-6842-11ea-9fe1-1f6bfb6be933.png">

dead-ends at https://github.com/cuelang/cue/blob/master/doc/tutorial/basics/Readme.md

Instead it should link to https://cuelang.org/docs/tutorials/tour/intro/, the first page of the tour.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/80.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
