### ISSUE TITLE
netlify: move to open source plan

### ISSUE THREAD

**Issue by myitcv** [cuelang/cuelang.org#83]
Consider switching to the Netlify open source plan, which is the same as the [pro plan](https://www.netlify.com/pricing/#teams) with unlimited team members.

Per https://www.netlify.com/legal/open-source-policy/ we must satisfy the following to qualify:

> * [x] Includes a license listed on the Open Source Initiative approved license list or a Creative Commons license that includes “attribution” or places the work in the public domain
> * [ ] Features a Code of Conduct at the top level directory of the project repository or prominently in the documentation (with a link in the navigation, footer, or homepage).
>   * _Possibly create a specific `CONDUCT.md` file in the repo root_
>   * _Need to add link from the site to the conduct file_
> * [ ] Must feature a link to our service on your main page
>   * _Need to add link to home page_ 
> * [x] Must not be a commercial project, whether created by a company or an individual. This prohibition includes commercial support and hosting services.
  
cc @mpvl

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/83.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
