### ISSUE TITLE
Broken formatting in https://cuelang.org/docs/usecases/datadef/

### ISSUE THREAD

**Issue by rutsky** [cuelang/cuelang.org#86]
On https://cuelang.org/docs/usecases/datadef/ code formatting is broken (notice e.g. `&amp;`):

![image](https://user-images.githubusercontent.com/46573/77227148-538ca900-6b7e-11ea-82f9-9e92b71b7079.png)

Matching source file:
https://github.com/cuelang/cuelang.org/blob/master/content/en/docs/usecases/datadef.md

**Comment by myitcv** [comment]
Thanks for raising this. Apologies that it's taken so long to get round to looking at this. 

The problem you described was fixed (recently) in https://github.com/cuelang/cuelang.org/pull/152

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cuelang.org/issues/86.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
