### ISSUE TITLE
Schema Definition: add comparison to SHACL

### ISSUE THREAD

**Issue by ludovicc** [cuelang/cuelang.org#94]
SHACL (https://www.w3.org/TR/shacl/) is a W3C constraint language for RDF and JSON. Its goals are similar to CUE, but restricted to semantic web technologies. It can be used to validate real world data (https://www.semanticarts.com/whats-exciting-about-shacl-rdf-data-shapes/)

Can you provide a comparison between SHACL and CUE?

**Comment by myitcv** [comment]
cc @mpvl

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1988.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
